'use client';

import { Eye, Download } from 'lucide-react';

export default function ReportsTable() {
  const reports = [
    { id: 1, name: 'Monthly Payroll', category: 'Payroll', generatedBy: 'Admin', date: '01 Jun 2026', format: 'PDF' },
    { id: 2, name: 'Attendance Report', category: 'Attendance', generatedBy: 'HR', date: '01 Jun 2026', format: 'Excel' },
    { id: 3, name: 'Leave Summary', category: 'Leave', generatedBy: 'Admin', date: '31 May 2026', format: 'PDF' },
    { id: 4, name: 'Employee Performance', category: 'Performance', generatedBy: 'HR Manager', date: '30 May 2026', format: 'Excel' },
    { id: 5, name: 'Salary Register', category: 'Payroll', generatedBy: 'Admin', date: '30 May 2026', format: 'PDF' },
  ];

  const handleView = (id: number) => {
    alert(`Viewing report ${id}`);
  };

  const handleDownload = (id: number) => {
    alert(`Downloading report ${id}`);
  };

  return (
    <div>
      <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4">Generated Reports</h2>
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-zinc-200 dark:border-zinc-700">
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Report Name</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Category</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Generated By</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Date</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Format</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-zinc-700 dark:text-zinc-300">Action</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.id} className="border-b border-zinc-100 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="py-3 px-4 text-sm font-medium text-zinc-900 dark:text-zinc-100">{report.name}</td>
                <td className="py-3 px-4 text-sm text-zinc-600 dark:text-zinc-400">{report.category}</td>
                <td className="py-3 px-4 text-sm text-zinc-600 dark:text-zinc-400">{report.generatedBy}</td>
                <td className="py-3 px-4 text-sm text-zinc-600 dark:text-zinc-400">{report.date}</td>
                <td className="py-3 px-4">
                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-semibold bg-zinc-100 text-zinc-700">
                    {report.format}
                  </span>
                </td>
                <td className="py-3 px-4">
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleView(report.id)}
                      className="p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors"
                      title="View"
                    >
                      <Eye className="h-4 w-4" />
                    </button>
                    <button
                      onClick={() => handleDownload(report.id)}
                      className="p-2 text-zinc-600 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-lg transition-colors"
                      title="Download"
                    >
                      <Download className="h-4 w-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
