'use client';

import { Download, Plus, Bell, FileText, FileSpreadsheet } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Button from '@/components/ui/Button/Button';
import { useState } from 'react';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import autoTable from 'jspdf-autotable';

const verticals = [
  { value: 'all', label: 'All Verticals' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'hotels', label: 'Hotels' },
  { value: 'saree', label: 'Saree Manufacturing' },
  { value: 'ho', label: 'Corporate Office' },
];

const dateFilters = ['Today', 'Week', 'Month', 'Custom'];

interface OverviewHeaderProps {
  stats?: {
    totalEmployees: number;
    presentToday: number;
    absentToday: number;
    lateArrivals: number;
    outdoorDuty: number;
    onLeave: number;
    newJoinees: number;
    exits: number;
  };
  dateRange?: {
    startDate: string;
    endDate: string;
  };
  userData?: any;
  userId?: string;
}

export default function OverviewHeader({ stats, dateRange, userData, userId }: OverviewHeaderProps) {
  const [showDownloadOptions, setShowDownloadOptions] = useState(false);
  const router = useRouter();

  const handleAlertsClick = () => {
    if (userId) {
      router.push(`/dashboard/hr_manager/${userId}/notifications`);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Header section
    doc.setFillColor(148, 203, 61); // #94cb3d - Coral Group green
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Coral Group HRMS Dashboard', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('HR Manager Overview Report', pageWidth / 2, 30, { align: 'center' });
    
    // Report metadata
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 55);
    doc.text(`Report Period: ${dateRange?.startDate} to ${dateRange?.endDate}`, 20, 62);
    if (userData?.data?.name) {
      doc.text(`Generated by: ${userData.data.name}`, 20, 69);
    }
    
    // Statistics table
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Metrics Summary', 20, 85);
    
    const tableData = [
      ['Metric', 'Value', 'Percentage', 'Status'],
      ['Total Employees', stats?.totalEmployees?.toString() || '0', '100%', 'Active'],
      ['Present Today', stats?.presentToday?.toString() || '0', stats?.totalEmployees ? `${((stats.presentToday / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Present'],
      ['Absent Today', stats?.absentToday?.toString() || '0', stats?.totalEmployees ? `${((stats.absentToday / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Absent'],
      ['Late Arrivals', stats?.lateArrivals?.toString() || '0', stats?.totalEmployees ? `${((stats.lateArrivals / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Late'],
      ['Outdoor Duty', stats?.outdoorDuty?.toString() || '0', stats?.totalEmployees ? `${((stats.outdoorDuty / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'On Field'],
      ['On Leave', stats?.onLeave?.toString() || '0', stats?.totalEmployees ? `${((stats.onLeave / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'On Leave'],
      ['New Joinees (30d)', stats?.newJoinees?.toString() || '0', stats?.totalEmployees ? `${((stats.newJoinees / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'New'],
      ['Exits (30d)', stats?.exits?.toString() || '0', stats?.totalEmployees ? `${((stats.exits / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Exit'],
    ];
    
    autoTable(doc, {
      startY: 95,
      head: [['Metric', 'Value', 'Percentage', 'Status']],
      body: tableData.slice(1),
      theme: 'grid',
      headStyles: {
        fillColor: [148, 203, 61],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      styles: {
        fontSize: 9,
        cellPadding: 5,
      },
    });
    
    // Footer
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(128, 128, 128);
    doc.text('This report is automatically generated by Coral Group HRMS System.', pageWidth / 2, finalY, { align: 'center' });
    doc.text('For detailed analysis, please refer to the Excel export.', pageWidth / 2, finalY + 7, { align: 'center' });
    
    doc.save(`HRMS_Dashboard_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    setShowDownloadOptions(false);
  };

  const handleDownloadExcel = () => {
    const data = [
      ['Coral Group HRMS Dashboard Report', '', '', ''],
      ['Generated on', new Date().toLocaleString(), '', ''],
      ['Report Period', `${dateRange?.startDate} to ${dateRange?.endDate}`, '', ''],
      ['Generated by', userData?.data?.name || 'HR Manager', '', ''],
      ['', '', '', ''],
      ['Metric', 'Value', 'Percentage', 'Status'],
      ['Total Employees', stats?.totalEmployees?.toString() || '0', '100%', 'Active'],
      ['Present Today', stats?.presentToday?.toString() || '0', stats?.totalEmployees ? `${((stats.presentToday / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Present'],
      ['Absent Today', stats?.absentToday?.toString() || '0', stats?.totalEmployees ? `${((stats.absentToday / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Absent'],
      ['Late Arrivals', stats?.lateArrivals?.toString() || '0', stats?.totalEmployees ? `${((stats.lateArrivals / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Late'],
      ['Outdoor Duty', stats?.outdoorDuty?.toString() || '0', stats?.totalEmployees ? `${((stats.outdoorDuty / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'On Field'],
      ['On Leave', stats?.onLeave?.toString() || '0', stats?.totalEmployees ? `${((stats.onLeave / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'On Leave'],
      ['New Joinees (30d)', stats?.newJoinees?.toString() || '0', stats?.totalEmployees ? `${((stats.newJoinees / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'New'],
      ['Exits (30d)', stats?.exits?.toString() || '0', stats?.totalEmployees ? `${((stats.exits / stats.totalEmployees) * 100).toFixed(1)}%` : '0%', 'Exit'],
    ];

    const ws = XLSX.utils.aoa_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Dashboard Report');
    XLSX.writeFile(wb, `HRMS_Dashboard_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
    setShowDownloadOptions(false);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50">
            HRMS Dashboard – Admin Overview
          </h1>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
            Real-time workforce analytics across all verticals
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          
          <Button 
            variant="primary" 
            size="sm"
            onClick={() => {
              const uniqueId = Math.random().toString(36).substring(2, 15);
              window.open(`/newjoining/form/${uniqueId}`, '_blank');
            }}
          >
            <Plus className="h-4 w-4" />
            New Employee Joining
          </Button>
          <div className="relative">
            <Button 
              variant="secondary" 
              size="sm"
              onClick={() => setShowDownloadOptions(!showDownloadOptions)}
            >
              <Download className="h-4 w-4" />
              Download Report
            </Button>
            {showDownloadOptions && (
              <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-zinc-900 rounded-lg shadow-lg border border-zinc-200 dark:border-zinc-800 z-10">
                <button
                  type="button"
                  onClick={handleDownloadPDF}
                  className="w-full flex items-center gap-2 px-4 py-3 text-sm text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors rounded-t-lg"
                >
                  <FileText className="h-4 w-4" />
                  Download as PDF
                </button>
                <button
                  type="button"
                  onClick={handleDownloadExcel}
                  className="w-full flex items-center gap-2 px-4 py-3 text-sm text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors rounded-b-lg"
                >
                  <FileSpreadsheet className="h-4 w-4" />
                  Download as Excel
                </button>
              </div>
            )}
          </div>
          <Button variant="ghost" size="sm" onClick={handleAlertsClick}>
            <Bell className="h-4 w-4" />
            Alerts
          </Button>
        </div>
      </div>

      {/* <div className="flex flex-wrap items-center gap-3">
        <select className="rounded-lg border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-3 py-2 text-sm text-zinc-900 dark:text-zinc-50 focus:outline-none focus:ring-2 focus:ring-[#94cb3d]/50">
          {verticals.map((v) => (
            <option key={v.value} value={v.value}>{v.label}</option>
          ))}
        </select>

        <div className="flex items-center rounded-lg border border-zinc-300 dark:border-zinc-700 overflow-hidden">
          {dateFilters.map((f, i) => (
            <button
              key={f}
              type="button"
              className={`px-3 py-2 text-xs font-medium transition-colors ${
                i === 0
                  ? 'bg-[#94cb3d] text-white'
                  : 'bg-white dark:bg-zinc-900 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-50 dark:hover:bg-zinc-800'
              }`}
            >
              {f}
            </button>
          ))}
        </div> */}
      {/* </div> */}
    </div>
  );
}
